services:
  - type: web
    name: n8n
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: SUPABASE_URL
        value: 'https://vdzzppefrijatkqcoaxd.supabase.co'
      - key: SUPABASE_KEY
        value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkenpwcGVmcmlqYXRrcWNvYXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTQyMzIsImV4cCI6MjA1NjU5MDIzMn0.NPRVR2u3oN5Vjo3T-gcUK22Lbyl1xUQJY3xOGDZrdzE'
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: starter
